web:
  build: .
  volumes:
    - ./src:/usr/src/app
  working_dir: /usr/src/app
  environment:
    - NODE_PATH=/install/node_modules
    - NODE_ENV=development
  entrypoint: npm start
  ports:
    - "3000:3000"
  expose:
    - "3000"
